### ISSUE TITLE
status.ropensci.org display issues?

### ISSUE THREAD

**Issue by cboettig** [ropensci/roweb#159]
I no longer see any of the icons on the top of page indicating what column is what.  Also not seeing sparklines for most of the repos.  strange.  Is this working for you? Screenshot below

![screen](https://cloud.githubusercontent.com/assets/222586/5967467/1f725726-a7c2-11e4-91ef-bbdddee7c167.png)

**Comment by karthik** [comment]
Thanks for the bug report. It's been fixed (do a hard refresh). Future bug reports should go on the jumpin repo. Cheers.

**Comment by cboettig** [comment]
Thanks for the quick fix. Looked good yesterday, now I'm seeing all the icons but still missing lots of sparklines. (Sorry for getting the wrong repo for the bug report)

**Comment by karthik** [comment]
Good catch, looking into it now.

**Comment by karthik** [comment]
Fixed. The API calls are made daily. If they fail, so will the sparkline
(it will be blank). Because we don't hold any state in a database, there is
no way to not stop this from happening from time to time. I'll see if I can
come up with a hack that doesn't rely on a saved state.
