### ISSUE TITLE
Post on our increasing geospatial stack

### ISSUE THREAD

**Issue by sckott** [ropensci/roweb#160]
* geojsonio
* wellknown
* spocc?
* gistr (ish? to share maps)
* others?

wait a while, since there may be turf.js action at hackathon, etc.

**Comment by karthik** [comment]
I suggest we go ahead without `turf.js`. Morgan will likely attend, but by the time all that is done, we'll be into April.

**Comment by sckott** [comment]
okay, good good

**Comment by sckott** [comment]
closing this, wrapping into #166
