### ISSUE TITLE
spocc tutorial is broken

### ISSUE THREAD

**Issue by karthik** [ropensci/roweb#163]
This page: http://ropensci.org/tutorials/spocc_tutorial.html

```r
spp <- c('Danaus plexippus','Accipiter striatus','Pinus contorta')
dat <- occ(query = spp, from = 'gbif', gbifopts = list(hasCoordinate = TRUE))
data <- occ2df(dat)
mapleaflet(data = data, dest = ".")
```

This bit of code. Two things:
a) `mapleaflet` now takes `dat` not `data`
b) data is a data.frame. `mapleaflet` is expecting a S3 object where data resides in `x$data`

**Comment by sckott** [comment]
should be fixed now

**Comment by karthik** [comment]
Thanks!

**Comment by rossmounce** [comment]
You've fixed this problem at the tutorial site (https://ropensci.org/tutorials/spocc_tutorial.html) but it's still up in the original broken form at the blog site: https://ropensci.org/blog/2014/03/17/spocc/

Guess which version I just tried to follow? :smile: 

```
spp <- c("Danaus plexippus", "Accipiter striatus", "Pinus contorta")
dat <- occ(query = spp, from = "gbif", gbifopts = list(georeferenced = TRUE))
# occ2df, as the name suggests converts data contained inside an occ class to a R data.frame
data <- occ2df(dat)
mapleaflet(data = data, dest = ".")
```

**Comment by rossmounce** [comment]
Also, in the updated `spocc` tutorial you now don't really give a worked through multi-species example. What would be the updated syntax for getting georeferenced records for say "Danaus plexippus", "Accipiter striatus", "Pinus contorta" and mapping them on the same map with different colour points for each species?

I had a look at doing this with `rgbif` and `rgbifmap` but could only successfully do it for one species at a time which isn't really what I want. Any pointers? A three-taxon example with 'spocc' or 'rbgbif' would be really useful for the documentation I think.

**Comment by sckott** [comment]
Thanks @rossmounce !

I'll update the tutorial for `spocc` `v0.5` as well - and see about updating the blog post

For both of the below questions: we've split out cleaning functions from `spocc` into a new package called `scrubr` and any mapping functions into a new package called `mapr`. `mapr` accepts the outputs from `spocc`, `rgbif`, and `dismo` (`dismo` simply returns data.frame's), and `mapr` has plotting functionality for ggplot2, ggmap, base plots, leaflet, gist maps. Some examples below for each of your questions. 

> What would be the updated syntax for getting georeferenced records for say "Danaus plexippus", "Accipiter striatus", "Pinus contorta" and mapping them on the same map with different colour points for each species?

The easiest way to do different symbols for each taxon is using github gists, via `map_gist()`

```r
library("spocc")
spp <- c('Danaus plexippus', 'Accipiter striatus', 'Pinus contorta')
dat <- occ(spp, from = 'gbif', limit=30, has_coords = TRUE)
map_gist(dat, color=c('#976AAE','#6B944D','#BD5945'))
```

![gist](http://f.cl.ly/items/0y213i3C3a1t0t3I1x2n/Screen%20Shot%202016-05-01%20at%2012.39.56%20PM.png)

> I had a look at doing this with rgbif and rgbifmap but could only successfully do it for one species at a time which isn't really what I want. Any pointers? A three-taxon example with 'spocc' or 'rbgbif' would be really useful for the documentation I think.

`rgbif` map function doesn't handle the output of multiple taxa - it's a dumb function - but here's an example, which I'll include in the docs as well and others to demonstrate how to handle many taxa

```r
library("rgbif")
splist <- c('Cyanocitta stelleri', 'Junco hyemalis', 'Aix sponsa')
keys <- vapply(splist, function(x) name_suggest(x)$key[1], numeric(1), USE.NAMES=FALSE)
dat <- occ_data(keys, limit = 50)
library("data.table")
dd <- rbindlist(lapply(dat, function(z) z$data), fill = TRUE, use.names = TRUE)
gbifmap(dd)
```

![gbif](http://f.cl.ly/items/2D1G3k3R0c360L2L3P12/Screen%20Shot%202016-05-01%20at%209.23.55%20AM.png)

-----

have on the to do list to allow diff. marker colors by taxon in the other fxns https://github.com/ropensci/mapr/issues/21

**Comment by rossmounce** [comment]
Brilliant, thank you sooo much for this. I will be making merry use of this tomorrow. Seems like I just can't keep up to date with all the new stuff at ropensci.  :beers:

**Comment by sckott** [comment]
all tutorials updated

**Comment by sckott** [comment]
@karthik any ideas, updated this blog post https://ropensci.org/blog/2014/03/17/spocc/ in the commit above this comment  - but it hasn't updated after rsyncing

**Comment by sckott** [comment]
@rossmounce Okay, reinstall `mapr`  `devtools::install_github("ropensci/mapr")` - I've added color pts by taxon to all functions - still some tweaking to do for sure
