### ISSUE TITLE
blog post describing technical challenges of creating the baad database

### ISSUE THREAD

**Issue by richfitz** [ropensci/roweb#167]
@dfalster is keen to write a blog post describing aspects of creating the [baad](https://github.com/dfalster/baad) - this is a major data synthesis effort that combines 176 studies of plant allometry.

We faced several challenges, including a lot of other people's data, coordinating error checking with many co-authors, and the lack of established tools while trying to be extremely transparent and reproducible.  The finished product compiles end-to-end from unmodified data files sent by authors and has been reproduced fairly widely.  This post could serve as pointers for people undertaking similar efforts.

**Comment by karthik** [comment]
That would be great and quite welcome!

**Comment by sckott** [comment]
sounds great @richfitz - we do have some blost posts to do, but none seem almost ready, so you're probably next :)

**Comment by sckott** [comment]
ready to go, see https://github.com/dfalster/baad_blog/pull/4

planning to post tomorrow morning
