### ISSUE TITLE
Post on the R wishlist

### ISSUE THREAD

**Issue by karthik** [ropensci/roweb#171]
Hey @Ironholds,
want to guest post on the R wishlist? If you're short on time I can do this or co-write with you. It would be a nice way to announce to the community and reach a broader audience that Twitter.

**Comment by Ironholds** [comment]
Totally! Later today work for you?

**Comment by karthik** [comment]
Wow, yes that would be awesome. :clap: :100: :rocket:

**Comment by sckott** [comment]
posted, tweeting tomorrow morning

**Comment by Ironholds** [comment]
Yay!
