### ISSUE TITLE
Read more link on home page is broken!

### ISSUE THREAD

**Issue by lmmx** [ropensci/roweb#173]
[This line](https://github.com/ropensci/ropensci.github.com/blob/master/index.html#L128) leading to [this link](http://ropensci.org/2011/07/31/welcome-to-ropensci/) on [the homepage](http://ropensci.github.io/) is a dead end, not sure where it's meant to lead... :confused:

**Comment by sckott** [comment]
thanks for this, fixed in ropensci/ropensci.github.com@f26732007f23df46a3ab2633763ad996afaae95f
