### ISSUE TITLE
https issues

### ISSUE THREAD

**Issue by karthik** [ropensci/roweb#174]
The site is partially SSL secured at this point. I suspect that `http` links in the liquid templates are giving that partial secure lock.  We have to go through the liquid template files and replace `http` with `https` or even just `//...`. 

Someone needs to check that this is ok for Disqus. 
Should be fine to replace all the `http` for the css files to `https`.

I'll wait another day or two for ASM to confirm that they don't have to do more to check my certificate install.

**Comment by sckott** [comment]
made a change to Disqus following https://help.disqus.com/customer/portal/articles/542119-can-disqus-be-loaded-via-https- - not all comments loading on our site, but they said could take up to 24 hrs. I'll check again tomorrow and if not working still, I'll troubleshoot

**Comment by sckott** [comment]
Some resources like images seem to be not loading either - perhaps we need to change permissions on those?

**Comment by karthik** [comment]
> Some resources like images seem to be not loading either - perhaps we need to change permissions on those?

Right, I see that the font-awesome links are gone. So I tried to find replace http links but realized that we don't have to do that (thank goodness for liquid templating). `{{site.url}}` should take care of it. So is that always just the root URL or can we hardcode it? @cboettig 

Also, how do we force http to https from now on?

**Comment by cboettig** [comment]
taking a look now

**Comment by cboettig** [comment]
Well some images seem to be missing because they are not in repository.  They must be working on ropensci.org because they were put there before and however you're deploying isn't erasing all the old stuff.

For instance, this image is missing: http://ropensci.org/assets/common-files/icons/browser-iphone@2x.png

On the repo, there's no `icons` dir in `assets/common-files`: https://github.com/ropensci/roweb/tree/master/assets/common-files

**Comment by karthik** [comment]
Good catch,
That is by design. You might recall that when we opened up the repo as CC-BY, I removed all copyrighted content so we could make the rest public. Since we `rsync` the rendered content to the server, it does not delete any content already there (only copies over new files or updates existing content). So that is the solution that has worked for us.

> Well some images seem to be missing because they are not in repository.

But on the server, when we run as `https`, all those files should resolve correctly. e.g.

```
https://ropensci.org/assets/common-files/icons/browser-iphone@2x.png
```

Are you talking about this affecting the local Docker preview? Otherwise I don't follow why this is a problem.

**Comment by cboettig** [comment]
@karthik Yup, I recall that's by design for the ss icons, wasn't sure if that image was also copyrighted.  

Good point, that would just affect (any local) preview.  Sorry.  was just poking around looking for said missing icons.  On what pages are the font-awesome icons located anyway?

**Comment by karthik** [comment]
That image isn't but given files of that name were at one point, it got purged. 

I think the missing icons that Scott and I see are on the main page. The down arrow to scroll below the hero image and also the copyright icon at the bottom of the front page. Those are the two that I spotted so far.

**Comment by karthik** [comment]
Particularly: 

1.  ![image](https://cloud.githubusercontent.com/assets/138494/6813959/51df3806-d237-11e4-8738-d1102992c61d.png)

2.  ![image](https://cloud.githubusercontent.com/assets/138494/6813961/57ed6100-d237-11e4-8876-9ddf22991f66.png)

**Comment by cboettig** [comment]
@karthik Right, but I don't understand how you're previewing this in the first place.  I also see that down arrow missing, but it's not a font-awesome icon, it's an ss icon, and like we just discussed those don't show up locally. AFAIK I'd have to either tell the page to use the full site path (with https now instead of http) in order for those icons to show up without being in the repo.

**Comment by karthik** [comment]
Oh right, I see them locally because I have a copy here. And right on the down arrow. It's actually `flat-ui` icon. 

> AFAIK I'd have to either tell the page to use the full site path (with https now instead of http) in order for those icons to show up without being in the repo.

I'm  more concerned that they are not rendering on the website when it works without https. I was always fine with local preview missing a few things (it doesn't cosmetically affect the site itself since it will all be fine when rendered).

**Comment by karthik** [comment]
And all of the css paths are relative. e..g. So if the root changes to `https`, they should all be so.

```css
@font-face {
  font-family: 'Lato';
  src: url('../fonts/lato/lato-black.eot');
  src: url('../fonts/lato/lato-black.eot?#iefix') format('embedded-opentype'), url('../fonts/lato/lato-black.woff') format('woff'), url('../fonts/lato/lato-black.ttf') format('truetype'), url('../fonts/lato/lato-black.svg#latoblack') format('svg');
  font-weight: 900;
  font-style: normal;
}
```

**Comment by karthik** [comment]
Looking at this now: http://stackoverflow.com/questions/7748140/font-face-eot-not-loading-over-https

**Comment by cboettig** [comment]
Interesting.  sorry didn't realize https://ropensci.org and http://ropensci.org were up at the same time.  Now I see the same errors you do.  The debug console shows these errors:



```
Failed to load resource: the server responded with a status of 403 (Forbidden)
https://ropensci.org/assets/css/ss-social/webfonts/ss-social-regular.woff Failed to load resource: the server responded with a status of 403 (Forbidden)
ZeroClipboard.swf:1 Uncaught SyntaxError: Unexpected token ILLEGAL
ropensci.org/:1 Mixed Content: The page at 'https://ropensci.org/' was loaded over HTTPS, but requested an insecure script 'http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML'. This request has been blocked; the content must be served over HTTPS.
https://ropensci.org/assets/common-files/fonts/Startup-Icons.ttf Failed to load resource: the server responded with a status of 403 (Forbidden)
https://ropensci.org/assets/css/ss-social/webfonts/ss-social-regular.ttf Failed to load resource: the server responded with a status of 403 (Forbidden)
https://ropensci.org/assets/flat-ui/fonts/flat-ui-icons-regular.woff Failed to load resource: the server responded with a status of 403 (Forbidden)
https://ropensci.org/assets/flat-ui/fonts/flat-ui-icons-regular.ttf Failed to load resource: the server responded with a status of 403 (Forbidden)
/assets/flat-ui/bootstrap/css/bootstrap.css.map:1 GET https://ropensci.org/assets/flat-ui/bootstrap/css/bootstrap.css.map 404 (Not Found)
```

**Comment by sckott** [comment]
zeroclipboard can be removed AFAIK - i was playing with it to try to add copy buttons for installation code on packages page, but didn't finish yet. Or maybe it's used for something else already?

**Comment by karthik** [comment]
Not yet Scott. Go ahead and remove it.

I also noticed this on incognito mode (see lock on top right is clean). Looks like my adblock is some of the problem. I'll dig deeper and see why those fonts are behaving badly. I think once those are fixed it should be fine.

![image](https://cloud.githubusercontent.com/assets/138494/6814418/9c38f7ee-d23b-11e4-87d5-8bb98dec31e3.png)

**Comment by karthik** [comment]
Looks like the lock is clean and green now. The font issues are independent and need some work.

**Comment by sckott** [comment]
removed zeroclipboard refernces

**Comment by karthik** [comment]
@sckott @cboettig https://ropensci.org works for me with no warnings. same for you two? If so next step is to force all http requests to https (not sure what is the best practice here. Something in `mod_rewrite` perhaps).

**Comment by cboettig** [comment]
Works fine from Ubuntu on Chrome and Firefox, but from Android tablet in
Chrome I'm seeing "invalid cert" right now (red 'back to safety' button in
chrome and all).  hmmm...

**Comment by sckott** [comment]
same for me, _invalid cert, go back to safety_ on android chrome and firefox

**Comment by sckott** [comment]
also, disqus isn't solved yet - e.g., compare https://ropensci.org/blog/2014/06/09/reproducibility/ to http://ropensci.org/blog/2014/06/09/reproducibility/ 

i went through steps they suggest, but they didn't work

**Comment by karthik** [comment]
Quick update: We're _almost_ there. Font issues are resolved. We can't go any higher on SSL rating since we're on shared hosting.

The last remaining challenge is a mod_rewrite issue that causes the page to stall on Safari (osx and ios). Hoping to get that resolved and we would be good to announce.

**Comment by sckott** [comment]
weird problem on Opera browser, message when hitting ropensci.org:

> This webpage has a redirect loop - The webpage at https://ropensci.org/ has resulted in too many redirects. Clearing your cookies for this site or allowing third-party cookies may fix the problem. If not, it is possibly a server configuration issue and not a problem with your computer

**Comment by karthik** [comment]
That is the same problem as safari.

**Comment by sckott** [comment]
works fine in Vivaldi, not that anyone uses it :/

**Comment by cboettig** [comment]
Glad we're getting close. someone will have to remind me why we wanted
https on ropensci.org though -- are we actually handling sensitive user
data or something now?

**Comment by sckott** [comment]
i think it's worth having for the discussion forum since users log in to the site, and i imagine https helps security on that front

**Comment by karthik** [comment]
Those are all SSL anyway. Twitter, Google etc don't authenticate in the open. Same thing with Disqus.
