### ISSUE TITLE
Possible https bug

### ISSUE THREAD

**Issue by karthik** [ropensci/roweb#177]
The iframe here with the Shiny app is not working.

https://ropensci.org/blog/2014/04/16/topic-modeling-in-R/

**Comment by sckott** [comment]
maybe we can do a screenshot, then link to the shiny server?

**Comment by karthik** [comment]
Sounds great. Otherwise it's just a blank thing. I can see a new banner load (RStudio shiny server) but nothing after that.

**Comment by karthik** [comment]
This got resolved.
