### ISSUE TITLE
post on unconf?

### ISSUE THREAD

**Issue by cboettig** [ropensci/roweb#178]
Do we have plans for a post on the unconf?  Might be good to check in with @arfon about the video recording of the panel on teaching, since that might be an easy thing to include in the post.

**Comment by sckott** [comment]
@karthik is this still happening? if not, let's close

**Comment by karthik** [comment]
@sckott Sorry I dropped the ball. And as more time went by, it became less and less relevant to talk about these in progress projects. So yes, let's close. Apologies.
