### ISSUE TITLE
Add Noam Ross to community page

### ISSUE THREAD

**Issue by karthik** [ropensci/roweb#183]
@noamross As mentioned in email, a picture and blurb would help us to get you on the page.

**Comment by noamross** [comment]
> Noam is a graduate student at University of California-Davis, studying disease dynamics, bioeconomics and optimal control. Noam contributes to the ArchieML package and contributes to the driver package.

![noam sac-002](https://cloud.githubusercontent.com/assets/571752/7149034/be21beda-e2bd-11e4-8bab-ff97c4af9a64.jpg)
