### ISSUE TITLE
add very brief description to each pkg on tutorials landing page?

### ISSUE THREAD

**Issue by sckott** [ropensci/roweb#184]
https://twitter.com/pssGuy/status/594190734971969536

maybe not though if it makes things too clutered

**Comment by karthik** [comment]
Sounds like a really good suggestion to me.

**Comment by sckott** [comment]
cool, can do

**Comment by richfitz** [comment]
This looks great. I wonder if it's worth adding the same thing here: http://ropensci.github.io/jumpin/ in which case it'd want to be done programmatically.

**Comment by sckott** [comment]
hmm, if we had an API for ropensci packages ...

**Comment by karthik** [comment]
Right not it reads the GItHub description and shows that as tooltip when you hover over a package name. I can redo this.
