### ISSUE TITLE
Some pages are garbled, not sure why

### ISSUE THREAD

**Issue by sckott** [ropensci/roweb#206]
e.g., https://ropensci.org/tutorials/fulltext_tutorial.html 

<img width="948" alt="screen shot 2015-09-29 at 9 00 19 am" src="https://cloud.githubusercontent.com/assets/577668/10170112/90272340-6688-11e5-89da-7fffc0f92fd6.png">

**Comment by karthik** [comment]
It's an issue we've seen before. If you close `</section>` tags, then kramdown cannot parse code blocks inside. If you leave section tags unclosed, it should work fine.

**Comment by sckott** [comment]
weird
