### ISSUE TITLE
Blog post on pdftools

### ISSUE THREAD

**Issue by sckott** [ropensci/roweb#225]

**Comment by jeroenooms** [comment]
I don't have permission to push a draft to this repo I think. Should I mail it to you?

**Comment by sckott** [comment]
Try again

**Comment by jeroenooms** [comment]
I added a [draft](https://github.com/ropensci/roweb/blob/master/_drafts/2016-03-01-pdftools-and-jeroen.md). @sckott or @karthik want to proofread and publish this? The last paragraph has an announcement about me as K suggested, but I don't like to write about myself so maybe someone else should revise that section :)

**Comment by sckott** [comment]
I'll have a look

**Comment by sckott** [comment]
Did you want to render output from some of the function calls in the post?

changed blog post parser to point to staff section for the link on your name  57c8dc934792486834226d2c94af0ed4334b8f77

**Comment by jeroenooms** [comment]
> Did you want to render output from some of the function calls in the post?

I don't think so, output is very verbose. What do you think?

**Comment by sckott** [comment]
Right, sound good to not include output

**Comment by jeroenooms** [comment]
Want me to fix those typos or are you committing them?

**Comment by sckott** [comment]
go ahead
