### ISSUE TITLE
New post on Travis-R

### ISSUE THREAD

**Issue by karthik** [ropensci/roweb#247]
@jeroenooms Best way is to just PR from a branch on the same repo so others can comment and provide feedback. That's what the rest of us do too.

**Comment by jeroenooms** [comment]
Here is a draft: https://github.com/ropensci/roweb/commit/744370da3efc0264e822d5c36849c2ecf5f10526. Thanks in advance for suggestions/proof reading. Feel free to publish if you think this is ready.

**Comment by jeroenooms** [comment]
Oh oops should have done a PR... committed straight to master. Will do next time :grin:

**Comment by sckott** [comment]
Sorry, should have suggested that, i'll have a look

**Comment by jeroenooms** [comment]
I've added an intro paragraph with references to Hadley's R-packages book and an RStudio blog post introducing Travis. Let's bump the date and publish today?

**Comment by sckott** [comment]
Looks good to go to me. 

@jeroenooms note that the link behind your name goes to https://ropensci.org/about/#staff - which is in the blog post processing code - which probably makes sense so people know you work here :)

pushing a tiny change, the slug for the post name was `tarvis-osx`

**Comment by sckott** [comment]
@karthik @jeroenooms should we post this?

**Comment by jeroenooms** [comment]
Yeah this is ready. I think @karthik has limited internet access this week, so if you and @cboettig think this is good to go, let's go ahead and publish it.

**Comment by sckott** [comment]
I'll ping Carl and see if he's good with it

**Comment by sckott** [comment]
i guess he's not around either. At this point I guess we could just wait until tomorrow morning so more eyes see it, and European time zone people will be up as well

**Comment by sckott** [comment]
its up
