### ISSUE TITLE
notes on creating new blog

### ISSUE THREAD

**Issue by sckott** [ropensci/roweb#257]
need a separate blog folder for the new blog 

![screen shot 2016-09-08 at 10 58 44 am](https://cloud.githubusercontent.com/assets/577668/18360592/710f8ade-75b3-11e6-97e2-b64960df0662.png)

within `_posts`, create new folder matching the category name

![screen shot 2016-09-08 at 10 58 57 am](https://cloud.githubusercontent.com/assets/577668/18360590/710d237a-75b3-11e6-878e-506c40e4d0c6.png)

for posts in the new category, include a category in the yaml metadata

![screen shot 2016-09-08 at 10 59 08 am](https://cloud.githubusercontent.com/assets/577668/18360591/710e4fc0-75b3-11e6-9254-8088cca36427.png)

in `/blog/index.html` https://github.com/ropensci/roweb/blob/master/blog/index.html#L27-L37  exclude `pt` posts, and now exclude posts with the new category name

in `/blog-pt/index.html` https://github.com/ropensci/roweb/blob/master/blog-pt/index.html#L28-L33 only cycle through posts that have the category name

**Comment by karthik** [comment]
That's what I did on the `tech-notes` branch: https://github.com/ropensci/roweb/tree/tech-notes

But for some reason, the index page renders but doesn't show the post.

**Comment by karthik** [comment]
Actually, it works!

**Comment by karthik** [comment]
@jeroenooms If you want to pull the `tech-notes` fork and add your post, we can get this up shortly.
