### ISSUE TITLE
Blog is broken

### ISSUE THREAD

**Issue by karthik** [ropensci/roweb#286]
There is now no pagination and all blog posts from day 1 (i.e. 2012) show on `ropensci.org/blog`

We'll need to figure out a way to do the tech-posts as a separate blog and not try to filter main blog posts by category (which fails because if there are two or more consecutive tech posts, the main blog page goes empty).

**Comment by sckott** [comment]
it's not broken, - that's what we agreed on since we had problems with pagination - as you mention

**Comment by karthik** [comment]
Right, wish we had time at all hands to play around. I'll try to move `technotes` into `technotes/_posts` and see if we can render a separate blog. Two issues:

It would split the rss feed.


Second (I'll start a new issue) is that we don't seem to appear on R-bloggers (or am I wrong?) Seems like most people get a majority of their traffic from there. @jeroenooms mentioned so too. Would be good to add in.

**Comment by jeroenooms** [comment]
The r-bloggers problem was due to case sensitive `r` vs `R` tags. It's now fixed via https://github.com/ropensci/roweb/commit/8e36dceb5f688e984693b683f38f842627f4d4ca.
