### ISSUE TITLE
taxonomy suite post

### ISSUE THREAD

**Issue by sckott** [ropensci/roweb#326]
https://github.com/ropensci/roweb/blob/master/_drafts/2017-07-27-taxonomy-suite.md

any thoughts on this @stefaniebutland @karthik @zachary-foster @EDiLD @cboettig 

i think we are planning to get this up Thursday morning

**Comment by zachary-foster** [comment]
Looks good to me! I made a few changes in wording and added a bit more detail to the taxonomy intro section, but don't feel obliged accept them all if you like it better how it was. Mostly just style choices. I am excited to see it come out!

**Comment by sckott** [comment]
thanks @zachary-foster !

**Comment by sckott** [comment]
closing in favor of #329
