### ISSUE TITLE
Text strikethrough not rendering on blog

### ISSUE THREAD

**Issue by batpigandme** [ropensci/roweb#350]
On the actual rendered htm for my [So you (don't) think you can review a package](https://ropensci.org/blog/blog/2017/08/22/first-package-review) post, there's a word that does not have a strikethrough, but that's stricken in the [Markdown](https://github.com/ropensci/roweb/blob/0e80a56ae802b2be285ddf6879181301832eb68d/_posts/2017-08-22-first-package-review.md#L36), and in the GitHub-rendered preview thereof.
 _n.b. I'm linking directly to line 36 here, but I can't figure out commenting in the md file, sorry_

Sorry if I'm missing an easy patch on my end, I just can't quite figure out how to control the final output there without editing the html file (to which I don't have access)!

Visual aids for the various docs/outputs below:

## [**"~ myself ~"**](https://ropensci.org/blog/blog/2017/08/22/first-package-review)
![you_doodle_2017-09-27t10_58_44z](https://user-images.githubusercontent.com/831732/30910419-bd180456-a352-11e7-9512-12fc06c40d2e.jpg)

## [**`~myself~`**](https://github.com/ropensci/roweb/blob/0e80a56ae802b2be285ddf6879181301832eb68d/_posts/2017-08-22-first-package-review.md#L36)
![you_doodle_2017-09-27t10_53_55z](https://user-images.githubusercontent.com/831732/30910432-cb098f3a-a352-11e7-9dad-6f92a7817224.jpg)

## [**~myself~**](https://github.com/ropensci/roweb/blob/0e80a56ae802b2be285ddf6879181301832eb68d/_posts/2017-08-22-first-package-review.md#L36)
![you_doodle_2017-09-27t10_55_17z](https://user-images.githubusercontent.com/831732/30910456-e31370aa-a352-11e7-8afc-abf927fc9c0d.jpg)

**Comment by sckott** [comment]
fixed :)

**Comment by batpigandme** [comment]
You're the best, @sckott! 🥇
