### ISSUE TITLE
Update ecoengine tutorial

### ISSUE THREAD

**Issue by karthik** [ropensci/roweb#65]
To show off some of the new features.

**Comment by sckott** [comment]
@karthik can you update this tutorial when you get a chanc

**Comment by karthik** [comment]
Although this is fixed, the formatting on the md broke in Jekyll. Not sure why all code blocks are now one big unformatted chunk of text.

**Comment by karthik** [comment]
@sckott Any idea why this page (http://ropensci.org/tutorials/ecoengine_tutorial.html) isn't parsing correctly?

**Comment by sckott** [comment]
@karthik taking a look

**Comment by sckott** [comment]
fixed now http://ropensci.org/tutorials/ecoengine_tutorial.html 

what jekyll version and ruby version did you use to generate? i have 

jekyll `2.3.0`
ruby `2.1.0p0`

**Comment by karthik** [comment]
Weird. I have:

`jekyll 2.5.3`
`ruby 2.2.0p0 (2014-12-25 revision 49005)`

Surprised that older ruby stopped rendering something it did all this time.
